# Configures the 'cargo audit' tool for this project
# Documentation: https://docs.rs/cargo-audit/latest/cargo_audit/config/struct.Config.html

[advisories]
ignore = [
  "RUSTSEC-2024-0370", # proc-macro-error unmaintained (transitive dependency) -> Handled in workflow for now
  "RUSTSEC-2025-0141", # bincode unmaintained (transitive via ableton-link-rs)
  "RUSTSEC-2024-0436", # paste unmaintained (transitive via wgpu)
]
