[package]
name = "mapmap-bevy"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"

[dependencies]
bevy = { version = "0.14.2", default-features = false, features = ["bevy_winit", "bevy_render", "bevy_pbr", "bevy_sprite", "bevy_core_pipeline", "bevy_asset", "multi-threaded"] }
mapmap-core = { path = "../mapmap-core" }
bevy_atmosphere = "0.9.1"
bevy_mod_outline = "0.8.3"
bevy_enoki = "0.2.2"
rand = "0.8.5"
image = "0.25.1"
parking_lot = "0.12.1"
